# Generated by Django 3.1.5 on 2021-01-23 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('name_rus', models.CharField(max_length=50)),
                ('name_eng', models.CharField(max_length=50)),
                ('name_tr', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('1950', 'Fifties'), ('1960', 'Sixties'), ('1970', 'Seventies'), ('1980', 'Eighties'), ('1990', 'Nineties'), ('2000', 'Zero'), ('2010', 'Teens'), ('2020', 'Twenties')], default='2020', max_length=20)),
                ('excerpt', models.CharField(max_length=150)),
                ('content_rus', models.TextField()),
                ('content_eng', models.TextField()),
                ('content_transliter', models.TextField()),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
